#include "tokijp.h"
#include "ui_tokijp.h"

tokijp::tokijp(QWidget *parent) :
  QMainWindow(parent),
  ui(new Ui::tokijp)
{
  ui->setupUi(this);
  setWindowTitle(QString("Toki Pona Kanji and Hiragana Compression Tool"));
  setWindowIcon(QIcon("/home/tate/Desktop/toki.png"));
}

tokijp::~tokijp(){
  delete ui;
}

void tokijp::on_ltj_clicked(){
  ui->japanesetext->setText(latintojp(ui->latintext->toPlainText()).trimmed());
}

void tokijp::on_jtl_clicked(){
  ui->latintext->setText(jptolatin(ui->japanesetext->toPlainText()).trimmed());
}

//compression/decompression functions:

QString tokijp::jptolatin(QString text){
  text.replace(QString(" "), QString(""));
  text.replace(QString("あ"), QString("a "));
  text.replace(QString("獣"), QString("akesi "));
  text.replace(QString("無"), QString("ala "));
  text.replace(QString("探"), QString("alasa "));
  text.replace(QString("全"), QString("ale "));
  text.replace(QString("下"), QString("anpa "));
  text.replace(QString("变"), QString("ante "));
  text.replace(QString("ぬ"), QString("anu "));
  text.replace(QString("待"), QString("awen "));
  text.replace(QString("ん"), QString("en "));
  text.replace(QString("市"), QString("esun "));
  text.replace(QString("物"), QString("ijo "));
  text.replace(QString("悪"), QString("ike "));
  text.replace(QString("具"), QString("ilo "));
  text.replace(QString("内"), QString("insa "));
  text.replace(QString("汚"), QString("jaki "));
  text.replace(QString("人"), QString("jan "));
  text.replace(QString("黄"), QString("jelo "));
  text.replace(QString("有"), QString("jo "));
  text.replace(QString("魚"), QString("kala "));
  text.replace(QString("音"), QString("kalama "));
  text.replace(QString("来"), QString("kama "));
  text.replace(QString("木"), QString("kasi "));
  text.replace(QString("能"), QString("ken "));
  text.replace(QString("使"), QString("kepeken "));
  text.replace(QString("果"), QString("kili "));
  text.replace(QString("又"), QString("kin "));
  text.replace(QString("切"), QString("kipisi "));
  text.replace(QString("石"), QString("kiwen "));
  text.replace(QString("空"), QString("kon "));
  text.replace(QString("色"), QString("kule "));
  text.replace(QString("聞"), QString("kute "));
  text.replace(QString("群"), QString("kulupu "));
  text.replace(QString("ら"), QString("la "));
  text.replace(QString("眠"), QString("lape "));
  text.replace(QString("青"), QString("laso "));
  text.replace(QString("首"), QString("lawa "));
  text.replace(QString("布"), QString("len "));
  text.replace(QString("冷"), QString("lete "));
  text.replace(QString("り"), QString("li "));
  text.replace(QString("小"), QString("lili "));
  text.replace(QString("糸"), QString("linja "));
  text.replace(QString("葉"), QString("lipu "));
  text.replace(QString("赤"), QString("loje "));
  text.replace(QString("在"), QString("lon "));
  text.replace(QString("手"), QString("luka "));
  text.replace(QString("見"), QString("lukin "));
  text.replace(QString("穴"), QString("lupa "));
  text.replace(QString("土"), QString("ma "));
  text.replace(QString("母"), QString("mama "));
  text.replace(QString("貝"), QString("mani "));
  text.replace(QString("女"), QString("meli "));
  text.replace(QString("私"), QString("mi "));
  text.replace(QString("男"), QString("mije "));
  text.replace(QString("食"), QString("moku "));
  text.replace(QString("死"), QString("moli "));
  text.replace(QString("後"), QString("monsi "));
  text.replace(QString("む"), QString("mu "));
  text.replace(QString("月"), QString("mun "));
  text.replace(QString("楽"), QString("musi "));
  text.replace(QString("多"), QString("mute "));
  text.replace(QString("冗"), QString("namako "));
  text.replace(QString("番"), QString("nanpa "));
  text.replace(QString("狂"), QString("nasa "));
  text.replace(QString("道"), QString("nasin "));
  text.replace(QString("丘"), QString("nena "));
  text.replace(QString("此"), QString("ni "));
  text.replace(QString("称"), QString("nimi "));
  text.replace(QString("足"), QString("noka "));
  text.replace(QString("目"), QString("oko "));
  text.replace(QString("愛"), QString("olin "));
  text.replace(QString("彼"), QString("ona "));
  text.replace(QString("開"), QString("open "));
  text.replace(QString("打"), QString("pakala "));
  text.replace(QString("作"), QString("pali "));
  text.replace(QString("棒"), QString("palisa "));
  text.replace(QString("米"), QString("pan "));
  text.replace(QString("授"), QString("pana "));
  text.replace(QString("氏"), QString("pata "));
  text.replace(QString("ぴ"), QString("pi "));
  text.replace(QString("心"), QString("pilin "));
  text.replace(QString("黒"), QString("pimeja "));
  text.replace(QString("終"), QString("pini "));
  text.replace(QString("虫"), QString("pipi "));
  text.replace(QString("側"), QString("poka "));
  text.replace(QString("箱"), QString("poki "));
  text.replace(QString("良"), QString("pona "));
  text.replace(QString("同"), QString("sama "));
  text.replace(QString("火"), QString("seli "));
  text.replace(QString("皮"), QString("selo "));
  text.replace(QString("何"), QString("seme "));
  text.replace(QString("上"), QString("sewi "));
  text.replace(QString("体"), QString("sijelo "));
  text.replace(QString("丸"), QString("sike "));
  text.replace(QString("新"), QString("sin "));
  text.replace(QString("君"), QString("sina "));
  text.replace(QString("前"), QString("sinpin "));
  text.replace(QString("画"), QString("sitelen "));
  text.replace(QString("知"), QString("sona "));
  text.replace(QString("猫"), QString("soweli "));
  text.replace(QString("大"), QString("suli "));
  text.replace(QString("日"), QString("suno "));
  text.replace(QString("面"), QString("supa "));
  text.replace(QString("甜"), QString("suwi "));
  text.replace(QString("因"), QString("tan "));
  text.replace(QString("許"), QString("taso "));
  text.replace(QString("去"), QString("tawa "));
  text.replace(QString("水"), QString("telo "));
  text.replace(QString("时"), QString("tenpo "));
  text.replace(QString("言"), QString("toki "));
  text.replace(QString("家"), QString("tomo "));
  text.replace(QString("二"), QString("tu "));
  text.replace(QString("盛"), QString("unpa "));
  text.replace(QString("口"), QString("uta "));
  text.replace(QString("戦"), QString("utala "));
  text.replace(QString("白"), QString("walo "));
  text.replace(QString("一"), QString("wan "));
  text.replace(QString("鳥"), QString("waso "));
  text.replace(QString("力"), QString("wawa "));
  text.replace(QString("遥"), QString("weka "));
  text.replace(QString("要"), QString("wile "));
  text.replace(QString("粉"), QString("ko "));
  text.replace(QString("あ"), QString("a "));
  text.replace(QString("お"), QString("o "));
  text.replace(QString("え"), QString("e "));
  //end of sentence:
  text.replace(QString("。"), QString("."));
  //fix character mauling:
  text.replace(QString(" ."), QString(". "));
  text.replace(QString(" :"), QString(": "));
  text.replace(QString(" ?"), QString("? "));
  text.replace(QString(" ？"), QString("? "));//japanese question mark should probably be used
  return text;
}

QString tokijp::latintojp(QString text){
  text=QString(" ")+text+QString(" ");//spcaces improove word identification
  text.replace(QString("\n"), QString(" \n "));//spcaces improove word identification

  //basic words:
  text.replace(QString("akesi "),QString("獣"));
  text.replace(QString("alasa "), QString("探"));
  text.replace(QString("ale "), QString("全"));
  text.replace(QString("ali "), QString("全"));
  text.replace(QString("anpa "), QString("下"));
  text.replace(QString("ante "), QString("变"));
  text.replace(QString("anu "), QString("ぬ"));
  text.replace(QString("awen "), QString("待"));
  text.replace(QString("esun "), QString("市"));
  text.replace(QString("ijo "), QString("物"));
  text.replace(QString("ike "), QString("悪"));
  text.replace(QString("ilo "), QString("具"));
  text.replace(QString("insa "), QString("内"));
  text.replace(QString("jaki "), QString("汚"));
  text.replace(QString("jan "), QString("人"));
  text.replace(QString("jo "), QString("有"));
  text.replace(QString("kala "), QString("魚"));
  text.replace(QString("kalama "), QString("音"));
  text.replace(QString("kama "), QString("来"));
  text.replace(QString("kasi "), QString("木"));
  text.replace(QString("kepeken "), QString("使"));
  text.replace(QString("kili "), QString("果"));
  text.replace(QString("kipisi "), QString("切"));
  text.replace(QString("kiwen "), QString("石"));
  text.replace(QString("kon "), QString("空"));
  text.replace(QString("kule "), QString("色"));
  text.replace(QString("kute "), QString("聞"));
  text.replace(QString("kulupu "), QString("群"));
  text.replace(QString("lape "), QString("眠"));
  text.replace(QString("laso "), QString("青"));
  text.replace(QString("lawa "), QString("首"));
  text.replace(QString("lete "), QString("冷"));
  text.replace(QString("lili "), QString("小"));
  text.replace(QString("linja "), QString("糸"));
  text.replace(QString("lipu "), QString("葉"));
  text.replace(QString("loje "), QString("赤"));
  text.replace(QString("lon "), QString("在"));
  text.replace(QString("luka "), QString("手"));
  text.replace(QString("lukin "), QString("見"));
  text.replace(QString("lupa "), QString("穴"));
  text.replace(QString("mama "), QString("母"));
  text.replace(QString("mani "), QString("貝"));
  text.replace(QString("meli "), QString("女"));
  text.replace(QString("mije "), QString("男"));
  text.replace(QString("moku "), QString("食"));
  text.replace(QString("moli "), QString("死"));
  text.replace(QString("monsi "), QString("後"));
  text.replace(QString("mu "), QString("む"));
  text.replace(QString("mun "), QString("月"));
  text.replace(QString("musi "), QString("楽"));
  text.replace(QString("mute "), QString("多"));
  text.replace(QString("namako "), QString("冗"));
  text.replace(QString("nanpa "), QString("番"));
  text.replace(QString("nasa "), QString("狂"));
  text.replace(QString("nasin "), QString("道"));
  text.replace(QString("nena "), QString("丘"));
  text.replace(QString("nimi "), QString("称"));
  text.replace(QString("noka "), QString("足"));
  text.replace(QString("oko "), QString("目"));
  text.replace(QString("olin "), QString("愛"));
  text.replace(QString("open "), QString("開"));
  text.replace(QString("pakala "), QString("打"));
  text.replace(QString("pali "), QString("作"));
  text.replace(QString("palisa "), QString("棒"));
  text.replace(QString("pan "), QString("米"));
  text.replace(QString("pana "), QString("授"));
  text.replace(QString("pata "), QString("氏"));
  text.replace(QString("pilin "), QString("心"));
  text.replace(QString("pimeja "), QString("黒"));
  text.replace(QString("pini "), QString("終"));
  text.replace(QString("pipi "), QString("虫"));
  text.replace(QString("poka "), QString("側"));
  text.replace(QString("poki "), QString("箱"));
  text.replace(QString("pona "), QString("良"));
  text.replace(QString("sama "), QString("同"));
  text.replace(QString("seli "), QString("火"));
  text.replace(QString("selo "), QString("皮"));
  text.replace(QString("seme "), QString("何"));
  text.replace(QString("sewi "), QString("上"));
  text.replace(QString("sijelo "), QString("体"));
  text.replace(QString("sike "), QString("丸"));
  text.replace(QString("sin "), QString("新"));
  text.replace(QString("sina "), QString("君"));
  text.replace(QString("sinpin "), QString("前"));
  text.replace(QString("sitelen "), QString("画"));
  text.replace(QString("sona "), QString("知"));
  text.replace(QString("soweli "), QString("猫"));
  text.replace(QString("suli "), QString("大"));
  text.replace(QString("suno "), QString("日"));
  text.replace(QString("supa "), QString("面"));
  text.replace(QString("suwi "), QString("甜"));
  text.replace(QString("tan "), QString("因"));
  text.replace(QString("taso "), QString("許"));
  text.replace(QString("tawa "), QString("去"));
  text.replace(QString("telo "), QString("水"));
  text.replace(QString("tenpo "), QString("时"));
  text.replace(QString("toki "), QString("言"));
  text.replace(QString("tomo "), QString("家"));
  text.replace(QString("tu "), QString("二"));
  text.replace(QString("unpa "), QString("盛"));
  text.replace(QString("uta "), QString("口"));
  text.replace(QString("utala "), QString("戦"));
  text.replace(QString("walo "), QString("白"));
  text.replace(QString("wan "), QString("一"));
  text.replace(QString("waso "), QString("鳥"));
  text.replace(QString("wawa "), QString("力"));
  text.replace(QString("weka "), QString("遥"));
  text.replace(QString("wile "), QString("要"));
  //endings of words must be placed after original replacements
  text.replace(QString("ona "), QString("彼"));
  text.replace(QString("ala "), QString("無"));
  text.replace(QString("kin "), QString("又"));
  text.replace(QString("jelo "), QString("黄"));
  text.replace(QString("ken "), QString("能"));
  text.replace(QString("li "), QString("り"));
  text.replace(QString("mi "), QString("私"));
  text.replace(QString("ma "), QString("土"));
  text.replace(QString("pi "), QString("ぴ"));
  text.replace(QString("ni "), QString("此"));
  text.replace(QString("len "), QString("布"));
  text.replace(QString("en "), QString("ん"));
  text.replace(QString("ko "), QString("粉"));
  text.replace(QString("la "), QString("ら"));
  text.replace(QString("a "), QString("あ"));
  text.replace(QString("o "), QString("お"));
  text.replace(QString("e "), QString("え"));


  //periods:
  text.replace(QString("akesi."),QString("獣。"));
  text.replace(QString("alasa."), QString("探。"));
  text.replace(QString("ale."), QString("全。"));
  text.replace(QString("ali."), QString("全。"));
  text.replace(QString("anpa."), QString("下。"));
  text.replace(QString("ante."), QString("变。"));
  text.replace(QString("anu."), QString("ぬ。"));
  text.replace(QString("awen."), QString("待。"));
  text.replace(QString("esun."), QString("市。"));
  text.replace(QString("ijo."), QString("物。"));
  text.replace(QString("ike."), QString("悪。"));
  text.replace(QString("ilo."), QString("具。"));
  text.replace(QString("insa."), QString("内。"));
  text.replace(QString("jaki."), QString("汚。"));
  text.replace(QString("jan."), QString("人。"));
  text.replace(QString("jo."), QString("有。"));
  text.replace(QString("kala."), QString("魚。"));
  text.replace(QString("kalama."), QString("音。"));
  text.replace(QString("kama."), QString("来。"));
  text.replace(QString("kasi."), QString("木。"));
  text.replace(QString("kepeken."), QString("使。"));
  text.replace(QString("kili."), QString("果。"));
  text.replace(QString("kipisi."), QString("切。"));
  text.replace(QString("kiwen."), QString("石。"));
  text.replace(QString("kon."), QString("空。"));
  text.replace(QString("kule."), QString("色。"));
  text.replace(QString("kute."), QString("聞。"));
  text.replace(QString("kulupu."), QString("群。"));
  text.replace(QString("lape."), QString("眠。"));
  text.replace(QString("laso."), QString("青。"));
  text.replace(QString("lawa."), QString("首。"));
  text.replace(QString("lete."), QString("冷。"));
  text.replace(QString("lili."), QString("小。"));
  text.replace(QString("linja."), QString("糸。"));
  text.replace(QString("lipu."), QString("葉。"));
  text.replace(QString("loje."), QString("赤。"));
  text.replace(QString("lon."), QString("在。"));
  text.replace(QString("luka."), QString("手。"));
  text.replace(QString("lukin."), QString("見。"));
  text.replace(QString("lupa."), QString("穴。"));
  text.replace(QString("mama."), QString("母。"));
  text.replace(QString("mani."), QString("貝。"));
  text.replace(QString("meli."), QString("女。"));
  text.replace(QString("mi."), QString("私。"));
  text.replace(QString("mije."), QString("男。"));
  text.replace(QString("moku."), QString("食。"));
  text.replace(QString("moli."), QString("死。"));
  text.replace(QString("monsi."), QString("後。"));
  text.replace(QString("mu."), QString("む。"));
  text.replace(QString("mun."), QString("月。"));
  text.replace(QString("musi."), QString("楽。"));
  text.replace(QString("mute."), QString("多。"));
  text.replace(QString("namako."), QString("冗。"));
  text.replace(QString("nanpa."), QString("番。"));
  text.replace(QString("nasa."), QString("狂。"));
  text.replace(QString("nasin."), QString("道。"));
  text.replace(QString("nena."), QString("丘。"));
  text.replace(QString("nimi."), QString("称。"));
  text.replace(QString("noka."), QString("足。"));
  text.replace(QString("oko."), QString("目。"));
  text.replace(QString("olin."), QString("愛。"));
  text.replace(QString("open."), QString("開。"));
  text.replace(QString("pakala."), QString("打。"));
  text.replace(QString("pali."), QString("作。"));
  text.replace(QString("palisa."), QString("棒。"));
  text.replace(QString("pan."), QString("米。"));
  text.replace(QString("pana."), QString("授。"));
  text.replace(QString("pata."), QString("氏。"));
  text.replace(QString("pilin."), QString("心。"));
  text.replace(QString("pimeja."), QString("黒。"));
  text.replace(QString("pini."), QString("終。"));
  text.replace(QString("pipi."), QString("虫。"));
  text.replace(QString("poka."), QString("側。"));
  text.replace(QString("poki."), QString("箱。"));
  text.replace(QString("pona."), QString("良。"));
  text.replace(QString("sama."), QString("同。"));
  text.replace(QString("seli."), QString("火。"));
  text.replace(QString("selo."), QString("皮。"));
  text.replace(QString("seme."), QString("何。"));
  text.replace(QString("sewi."), QString("上。"));
  text.replace(QString("sijelo."), QString("体。"));
  text.replace(QString("sike."), QString("丸。"));
  text.replace(QString("sin."), QString("新。"));
  text.replace(QString("sina."), QString("君。"));
  text.replace(QString("sinpin."), QString("前。"));
  text.replace(QString("sitelen."), QString("画。"));
  text.replace(QString("sona."), QString("知。"));
  text.replace(QString("soweli."), QString("猫。"));
  text.replace(QString("suli."), QString("大。"));
  text.replace(QString("suno."), QString("日。"));
  text.replace(QString("supa."), QString("面。"));
  text.replace(QString("suwi."), QString("甜。"));
  text.replace(QString("tan."), QString("因。"));
  text.replace(QString("taso."), QString("許。"));
  text.replace(QString("tawa."), QString("去。"));
  text.replace(QString("telo."), QString("水。"));
  text.replace(QString("tenpo."), QString("时。"));
  text.replace(QString("toki."), QString("言。"));
  text.replace(QString("tomo."), QString("家。"));
  text.replace(QString("tu."), QString("二。"));
  text.replace(QString("unpa."), QString("盛。"));
  text.replace(QString("uta."), QString("口。"));
  text.replace(QString("utala."), QString("戦。"));
  text.replace(QString("walo."), QString("白。"));
  text.replace(QString("wan."), QString("一。"));
  text.replace(QString("waso."), QString("鳥。"));
  text.replace(QString("wawa."), QString("力。"));
  text.replace(QString("weka."), QString("遥。"));
  text.replace(QString("wile."), QString("要。"));
  //common endings of words must be placed after original replacements
  text.replace(QString("ona."), QString("彼。"));
  text.replace(QString("ala."), QString("無。"));
  text.replace(QString("la."), QString("ら。"));
  text.replace(QString("kin."), QString("又。"));
  text.replace(QString("jelo."), QString("黄。"));
  text.replace(QString("ken."), QString("能。"));
  text.replace(QString("len."), QString("布。"));
  text.replace(QString("en."), QString("ん。"));
  text.replace(QString("pi."), QString("ぴ。"));
  text.replace(QString("ni."), QString("此。"));
  text.replace(QString("ma."), QString("土。"));
  text.replace(QString("li."), QString("り。"));
  text.replace(QString("ko."), QString("粉。"));
  text.replace(QString("a."), QString("あ。"));
  text.replace(QString("o."), QString("お。"));
  text.replace(QString("e."), QString("え。"));

  //question marks:
  text.replace(QString("akesi?"),QString("獣?"));
  text.replace(QString("alasa?"), QString("探?"));
  text.replace(QString("ale?"), QString("全?"));
  text.replace(QString("ali?"), QString("全?"));
  text.replace(QString("anpa?"), QString("下?"));
  text.replace(QString("ante?"), QString("变?"));
  text.replace(QString("anu?"), QString("ぬ?"));
  text.replace(QString("awen?"), QString("待?"));
  text.replace(QString("esun?"), QString("市?"));
  text.replace(QString("ijo?"), QString("物?"));
  text.replace(QString("ike?"), QString("悪?"));
  text.replace(QString("ilo?"), QString("具?"));
  text.replace(QString("insa?"), QString("内?"));
  text.replace(QString("jaki?"), QString("汚?"));
  text.replace(QString("jan?"), QString("人?"));
  text.replace(QString("jo?"), QString("有?"));
  text.replace(QString("kala?"), QString("魚?"));
  text.replace(QString("kalama?"), QString("音?"));
  text.replace(QString("kama?"), QString("来?"));
  text.replace(QString("kasi?"), QString("木?"));
  text.replace(QString("kepeken?"), QString("使?"));
  text.replace(QString("kili?"), QString("果?"));
  text.replace(QString("kipisi?"), QString("切?"));
  text.replace(QString("kiwen?"), QString("石?"));
  text.replace(QString("kon?"), QString("空?"));
  text.replace(QString("kule?"), QString("色?"));
  text.replace(QString("kute?"), QString("聞?"));
  text.replace(QString("kulupu?"), QString("群?"));
  text.replace(QString("lape?"), QString("眠?"));
  text.replace(QString("laso?"), QString("青?"));
  text.replace(QString("lawa?"), QString("首?"));
  text.replace(QString("lete?"), QString("冷?"));
  text.replace(QString("lili?"), QString("小?"));
  text.replace(QString("linja?"), QString("糸?"));
  text.replace(QString("lipu?"), QString("葉?"));
  text.replace(QString("loje?"), QString("赤?"));
  text.replace(QString("lon?"), QString("在?"));
  text.replace(QString("luka?"), QString("手?"));
  text.replace(QString("lukin?"), QString("見?"));
  text.replace(QString("lupa?"), QString("穴?"));
  text.replace(QString("mama?"), QString("母?"));
  text.replace(QString("mani?"), QString("貝?"));
  text.replace(QString("meli?"), QString("女?"));
  text.replace(QString("mi?"), QString("私?"));
  text.replace(QString("mije?"), QString("男?"));
  text.replace(QString("moku?"), QString("食?"));
  text.replace(QString("moli?"), QString("死?"));
  text.replace(QString("monsi?"), QString("後?"));
  text.replace(QString("mu?"), QString("む?"));
  text.replace(QString("mun?"), QString("月?"));
  text.replace(QString("musi?"), QString("楽?"));
  text.replace(QString("mute?"), QString("多?"));
  text.replace(QString("namako?"), QString("冗?"));
  text.replace(QString("nanpa?"), QString("番?"));
  text.replace(QString("nasa?"), QString("狂?"));
  text.replace(QString("nasin?"), QString("道?"));
  text.replace(QString("nena?"), QString("丘?"));
  text.replace(QString("nimi?"), QString("称?"));
  text.replace(QString("noka?"), QString("足?"));
  text.replace(QString("oko?"), QString("目?"));
  text.replace(QString("olin?"), QString("愛?"));
  text.replace(QString("open?"), QString("開?"));
  text.replace(QString("pakala?"), QString("打?"));
  text.replace(QString("pali?"), QString("作?"));
  text.replace(QString("palisa?"), QString("棒?"));
  text.replace(QString("pan?"), QString("米?"));
  text.replace(QString("pana?"), QString("授?"));
  text.replace(QString("pata?"), QString("氏?"));
  text.replace(QString("pilin?"), QString("心?"));
  text.replace(QString("pimeja?"), QString("黒?"));
  text.replace(QString("pini?"), QString("終?"));
  text.replace(QString("pipi?"), QString("虫?"));
  text.replace(QString("poka?"), QString("側?"));
  text.replace(QString("poki?"), QString("箱?"));
  text.replace(QString("pona?"), QString("良?"));
  text.replace(QString("sama?"), QString("同?"));
  text.replace(QString("seli?"), QString("火?"));
  text.replace(QString("selo?"), QString("皮?"));
  text.replace(QString("seme?"), QString("何?"));
  text.replace(QString("sewi?"), QString("上?"));
  text.replace(QString("sijelo?"), QString("体?"));
  text.replace(QString("sike?"), QString("丸?"));
  text.replace(QString("sin?"), QString("新?"));
  text.replace(QString("sina?"), QString("君?"));
  text.replace(QString("sinpin?"), QString("前?"));
  text.replace(QString("sitelen?"), QString("画?"));
  text.replace(QString("sona?"), QString("知?"));
  text.replace(QString("soweli?"), QString("猫?"));
  text.replace(QString("suli?"), QString("大?"));
  text.replace(QString("suno?"), QString("日?"));
  text.replace(QString("supa?"), QString("面?"));
  text.replace(QString("suwi?"), QString("甜?"));
  text.replace(QString("tan?"), QString("因?"));
  text.replace(QString("taso?"), QString("許?"));
  text.replace(QString("tawa?"), QString("去?"));
  text.replace(QString("telo?"), QString("水?"));
  text.replace(QString("tenpo?"), QString("时?"));
  text.replace(QString("toki?"), QString("言?"));
  text.replace(QString("tomo?"), QString("家?"));
  text.replace(QString("tu?"), QString("二?"));
  text.replace(QString("unpa?"), QString("盛?"));
  text.replace(QString("uta?"), QString("口?"));
  text.replace(QString("utala?"), QString("戦?"));
  text.replace(QString("walo?"), QString("白?"));
  text.replace(QString("wan?"), QString("一?"));
  text.replace(QString("waso?"), QString("鳥?"));
  text.replace(QString("wawa?"), QString("力?"));
  text.replace(QString("weka?"), QString("遥?"));
  text.replace(QString("wile?"), QString("要?"));
  //common endings of words must be placed after original replacements
  text.replace(QString("ona?"), QString("彼?"));
  text.replace(QString("ala?"), QString("無?"));
  text.replace(QString("la?"), QString("ら?"));
  text.replace(QString("kin?"), QString("又?"));
  text.replace(QString("jelo?"), QString("黄?"));
  text.replace(QString("ken?"), QString("能?"));
  text.replace(QString("len?"), QString("布?"));
  text.replace(QString("en?"), QString("ん?"));
  text.replace(QString("pi?"), QString("ぴ?"));
  text.replace(QString("ni?"), QString("此?"));
  text.replace(QString("ma?"), QString("土?"));
  text.replace(QString("li?"), QString("り?"));
  text.replace(QString("ko?"), QString("粉?"));
  text.replace(QString("a?"), QString("あ?"));
  text.replace(QString("o?"), QString("お?"));
  text.replace(QString("e?"), QString("え?"));

  //exclamation marks:
  text.replace(QString("akesi!"),QString("獣!"));
  text.replace(QString("alasa!"), QString("探!"));
  text.replace(QString("ale!"), QString("全!"));
  text.replace(QString("ali!"), QString("全!"));
  text.replace(QString("anpa!"), QString("下!"));
  text.replace(QString("ante!"), QString("变!"));
  text.replace(QString("anu!"), QString("ぬ!"));
  text.replace(QString("awen!"), QString("待!"));
  text.replace(QString("esun!"), QString("市!"));
  text.replace(QString("ijo!"), QString("物!"));
  text.replace(QString("ike!"), QString("悪!"));
  text.replace(QString("ilo!"), QString("具!"));
  text.replace(QString("insa!"), QString("内!"));
  text.replace(QString("jaki!"), QString("汚!"));
  text.replace(QString("jan!"), QString("人!"));
  text.replace(QString("jo!"), QString("有!"));
  text.replace(QString("kala!"), QString("魚!"));
  text.replace(QString("kalama!"), QString("音!"));
  text.replace(QString("kama!"), QString("来!"));
  text.replace(QString("kasi!"), QString("木!"));
  text.replace(QString("kepeken!"), QString("使!"));
  text.replace(QString("kili!"), QString("果!"));
  text.replace(QString("kipisi!"), QString("切!"));
  text.replace(QString("kiwen!"), QString("石!"));
  text.replace(QString("kon!"), QString("空!"));
  text.replace(QString("kule!"), QString("色!"));
  text.replace(QString("kute!"), QString("聞!"));
  text.replace(QString("kulupu!"), QString("群!"));
  text.replace(QString("lape!"), QString("眠!"));
  text.replace(QString("laso!"), QString("青!"));
  text.replace(QString("lawa!"), QString("首!"));
  text.replace(QString("lete!"), QString("冷!"));
  text.replace(QString("lili!"), QString("小!"));
  text.replace(QString("linja!"), QString("糸!"));
  text.replace(QString("lipu!"), QString("葉!"));
  text.replace(QString("loje!"), QString("赤!"));
  text.replace(QString("lon!"), QString("在!"));
  text.replace(QString("luka!"), QString("手!"));
  text.replace(QString("lukin!"), QString("見!"));
  text.replace(QString("lupa!"), QString("穴!"));
  text.replace(QString("mama!"), QString("母!"));
  text.replace(QString("mani!"), QString("貝!"));
  text.replace(QString("meli!"), QString("女!"));
  text.replace(QString("mi!"), QString("私!"));
  text.replace(QString("mije!"), QString("男!"));
  text.replace(QString("moku!"), QString("食!"));
  text.replace(QString("moli!"), QString("死!"));
  text.replace(QString("monsi!"), QString("後!"));
  text.replace(QString("mu!"), QString("む!"));
  text.replace(QString("mun!"), QString("月!"));
  text.replace(QString("musi!"), QString("楽!"));
  text.replace(QString("mute!"), QString("多!"));
  text.replace(QString("namako!"), QString("冗!"));
  text.replace(QString("nanpa!"), QString("番!"));
  text.replace(QString("nasa!"), QString("狂!"));
  text.replace(QString("nasin!"), QString("道!"));
  text.replace(QString("nena!"), QString("丘!"));
  text.replace(QString("nimi!"), QString("称!"));
  text.replace(QString("noka!"), QString("足!"));
  text.replace(QString("oko!"), QString("目!"));
  text.replace(QString("olin!"), QString("愛!"));
  text.replace(QString("open!"), QString("開!"));
  text.replace(QString("pakala!"), QString("打!"));
  text.replace(QString("pali!"), QString("作!"));
  text.replace(QString("palisa!"), QString("棒!"));
  text.replace(QString("pan!"), QString("米!"));
  text.replace(QString("pana!"), QString("授!"));
  text.replace(QString("pata!"), QString("氏!"));
  text.replace(QString("pilin!"), QString("心!"));
  text.replace(QString("pimeja!"), QString("黒!"));
  text.replace(QString("pini!"), QString("終!"));
  text.replace(QString("pipi!"), QString("虫!"));
  text.replace(QString("poka!"), QString("側!"));
  text.replace(QString("poki!"), QString("箱!"));
  text.replace(QString("pona!"), QString("良!"));
  text.replace(QString("sama!"), QString("同!"));
  text.replace(QString("seli!"), QString("火!"));
  text.replace(QString("selo!"), QString("皮!"));
  text.replace(QString("seme!"), QString("何!"));
  text.replace(QString("sewi!"), QString("上!"));
  text.replace(QString("sijelo!"), QString("体!"));
  text.replace(QString("sike!"), QString("丸!"));
  text.replace(QString("sin!"), QString("新!"));
  text.replace(QString("sina!"), QString("君!"));
  text.replace(QString("sinpin!"), QString("前!"));
  text.replace(QString("sitelen!"), QString("画!"));
  text.replace(QString("sona!"), QString("知!"));
  text.replace(QString("soweli!"), QString("猫!"));
  text.replace(QString("suli!"), QString("大!"));
  text.replace(QString("suno!"), QString("日!"));
  text.replace(QString("supa!"), QString("面!"));
  text.replace(QString("suwi!"), QString("甜!"));
  text.replace(QString("tan!"), QString("因!"));
  text.replace(QString("taso!"), QString("許!"));
  text.replace(QString("tawa!"), QString("去!"));
  text.replace(QString("telo!"), QString("水!"));
  text.replace(QString("tenpo!"), QString("时!"));
  text.replace(QString("toki!"), QString("言!"));
  text.replace(QString("tomo!"), QString("家!"));
  text.replace(QString("tu!"), QString("二!"));
  text.replace(QString("unpa!"), QString("盛!"));
  text.replace(QString("uta!"), QString("口!"));
  text.replace(QString("utala!"), QString("戦!"));
  text.replace(QString("walo!"), QString("白!"));
  text.replace(QString("wan!"), QString("一!"));
  text.replace(QString("waso!"), QString("鳥!"));
  text.replace(QString("wawa!"), QString("力!"));
  text.replace(QString("weka!"), QString("遥!"));
  text.replace(QString("wile!"), QString("要!"));
  //common endings of words must be placed after original replacements
  text.replace(QString("ona!"), QString("彼!"));
  text.replace(QString("ala!"), QString("無!"));
  text.replace(QString("la!"), QString("ら!"));
  text.replace(QString("kin!"), QString("又!"));
  text.replace(QString("jelo!"), QString("黄!"));
  text.replace(QString("ken!"), QString("能!"));
  text.replace(QString("len!"), QString("布!"));
  text.replace(QString("en!"), QString("ん!"));
  text.replace(QString("pi!"), QString("ぴ!"));
  text.replace(QString("ni!"), QString("此!"));
  text.replace(QString("ma!"), QString("土!"));
  text.replace(QString("li!"), QString("り!"));
  text.replace(QString("ko!"), QString("粉!"));
  text.replace(QString("a!"), QString("あ!"));
  text.replace(QString("o!"), QString("お!"));
  text.replace(QString("e!"), QString("え!"));

  //colons:
  text.replace(QString("akesi:"),QString("獣:"));
  text.replace(QString("alasa:"), QString("探:"));
  text.replace(QString("ale:"), QString("全:"));
  text.replace(QString("ali:"), QString("全:"));
  text.replace(QString("anpa:"), QString("下:"));
  text.replace(QString("ante:"), QString("变:"));
  text.replace(QString("anu:"), QString("ぬ:"));
  text.replace(QString("awen:"), QString("待:"));
  text.replace(QString("esun:"), QString("市:"));
  text.replace(QString("ijo:"), QString("物:"));
  text.replace(QString("ike:"), QString("悪:"));
  text.replace(QString("ilo:"), QString("具:"));
  text.replace(QString("insa:"), QString("内:"));
  text.replace(QString("jaki:"), QString("汚:"));
  text.replace(QString("jan:"), QString("人:"));
  text.replace(QString("jo:"), QString("有:"));
  text.replace(QString("kala:"), QString("魚:"));
  text.replace(QString("kalama:"), QString("音:"));
  text.replace(QString("kama:"), QString("来:"));
  text.replace(QString("kasi:"), QString("木:"));
  text.replace(QString("kepeken:"), QString("使:"));
  text.replace(QString("kili:"), QString("果:"));
  text.replace(QString("kipisi:"), QString("切:"));
  text.replace(QString("kiwen:"), QString("石:"));
  text.replace(QString("kon:"), QString("空:"));
  text.replace(QString("kule:"), QString("色:"));
  text.replace(QString("kute:"), QString("聞:"));
  text.replace(QString("kulupu:"), QString("群:"));
  text.replace(QString("lape:"), QString("眠:"));
  text.replace(QString("laso:"), QString("青:"));
  text.replace(QString("lawa:"), QString("首:"));
  text.replace(QString("lete:"), QString("冷:"));
  text.replace(QString("lili:"), QString("小:"));
  text.replace(QString("linja:"), QString("糸:"));
  text.replace(QString("lipu:"), QString("葉:"));
  text.replace(QString("loje:"), QString("赤:"));
  text.replace(QString("lon:"), QString("在:"));
  text.replace(QString("luka:"), QString("手:"));
  text.replace(QString("lukin:"), QString("見:"));
  text.replace(QString("lupa:"), QString("穴:"));
  text.replace(QString("mama:"), QString("母:"));
  text.replace(QString("mani:"), QString("貝:"));
  text.replace(QString("meli:"), QString("女:"));
  text.replace(QString("mi:"), QString("私:"));
  text.replace(QString("mije:"), QString("男:"));
  text.replace(QString("moku:"), QString("食:"));
  text.replace(QString("moli:"), QString("死:"));
  text.replace(QString("monsi:"), QString("後:"));
  text.replace(QString("mu:"), QString("む:"));
  text.replace(QString("mun:"), QString("月:"));
  text.replace(QString("musi:"), QString("楽:"));
  text.replace(QString("mute:"), QString("多:"));
  text.replace(QString("namako:"), QString("冗:"));
  text.replace(QString("nanpa:"), QString("番:"));
  text.replace(QString("nasa:"), QString("狂:"));
  text.replace(QString("nasin:"), QString("道:"));
  text.replace(QString("nena:"), QString("丘:"));
  text.replace(QString("nimi:"), QString("称:"));
  text.replace(QString("noka:"), QString("足:"));
  text.replace(QString("oko:"), QString("目:"));
  text.replace(QString("olin:"), QString("愛:"));
  text.replace(QString("open:"), QString("開:"));
  text.replace(QString("pakala:"), QString("打:"));
  text.replace(QString("pali:"), QString("作:"));
  text.replace(QString("palisa:"), QString("棒:"));
  text.replace(QString("pan:"), QString("米:"));
  text.replace(QString("pana:"), QString("授:"));
  text.replace(QString("pata:"), QString("氏:"));
  text.replace(QString("pilin:"), QString("心:"));
  text.replace(QString("pimeja:"), QString("黒:"));
  text.replace(QString("pini:"), QString("終:"));
  text.replace(QString("pipi:"), QString("虫:"));
  text.replace(QString("poka:"), QString("側:"));
  text.replace(QString("poki:"), QString("箱:"));
  text.replace(QString("pona:"), QString("良:"));
  text.replace(QString("sama:"), QString("同:"));
  text.replace(QString("seli:"), QString("火:"));
  text.replace(QString("selo:"), QString("皮:"));
  text.replace(QString("seme:"), QString("何:"));
  text.replace(QString("sewi:"), QString("上:"));
  text.replace(QString("sijelo:"), QString("体:"));
  text.replace(QString("sike:"), QString("丸:"));
  text.replace(QString("sin:"), QString("新:"));
  text.replace(QString("sina:"), QString("君:"));
  text.replace(QString("sinpin:"), QString("前:"));
  text.replace(QString("sitelen:"), QString("画:"));
  text.replace(QString("sona:"), QString("知:"));
  text.replace(QString("soweli:"), QString("猫:"));
  text.replace(QString("suli:"), QString("大:"));
  text.replace(QString("suno:"), QString("日:"));
  text.replace(QString("supa:"), QString("面:"));
  text.replace(QString("suwi:"), QString("甜:"));
  text.replace(QString("tan:"), QString("因:"));
  text.replace(QString("taso:"), QString("許:"));
  text.replace(QString("tawa:"), QString("去:"));
  text.replace(QString("telo:"), QString("水:"));
  text.replace(QString("tenpo:"), QString("时:"));
  text.replace(QString("toki:"), QString("言:"));
  text.replace(QString("tomo:"), QString("家:"));
  text.replace(QString("tu:"), QString("二:"));
  text.replace(QString("unpa:"), QString("盛:"));
  text.replace(QString("uta:"), QString("口:"));
  text.replace(QString("utala:"), QString("戦:"));
  text.replace(QString("walo:"), QString("白:"));
  text.replace(QString("wan:"), QString("一:"));
  text.replace(QString("waso:"), QString("鳥:"));
  text.replace(QString("wawa:"), QString("力:"));
  text.replace(QString("weka:"), QString("遥:"));
  text.replace(QString("wile:"), QString("要:"));
  //common endings of words must be placed after original replacements
  text.replace(QString("ona:"), QString("彼:"));
  text.replace(QString("ala:"), QString("無:"));
  text.replace(QString("la:"), QString("ら:"));
  text.replace(QString("kin:"), QString("又:"));
  text.replace(QString("jelo:"), QString("黄:"));
  text.replace(QString("ken:"), QString("能:"));
  text.replace(QString("len:"), QString("布:"));
  text.replace(QString("en:"), QString("ん:"));
  text.replace(QString("pi:"), QString("ぴ:"));
  text.replace(QString("ni:"), QString("此:"));
  text.replace(QString("ma:"), QString("土:"));
  text.replace(QString("li:"), QString("り:"));
  text.replace(QString("ko:"), QString("粉:"));
  text.replace(QString("a:"), QString("あ:"));
  text.replace(QString("o:"), QString("お:"));
  text.replace(QString("e:"), QString("え:"));

  //colons:
  text.replace(QString("akesi,"),QString("獣,"));
  text.replace(QString("alasa,"), QString("探,"));
  text.replace(QString("ale,"), QString("全,"));
  text.replace(QString("ali,"), QString("全,"));
  text.replace(QString("anpa,"), QString("下,"));
  text.replace(QString("ante,"), QString("变,"));
  text.replace(QString("anu,"), QString("ぬ,"));
  text.replace(QString("awen,"), QString("待,"));
  text.replace(QString("esun,"), QString("市,"));
  text.replace(QString("ijo,"), QString("物,"));
  text.replace(QString("ike,"), QString("悪,"));
  text.replace(QString("ilo,"), QString("具,"));
  text.replace(QString("insa,"), QString("内,"));
  text.replace(QString("jaki,"), QString("汚,"));
  text.replace(QString("jan,"), QString("人,"));
  text.replace(QString("jo,"), QString("有,"));
  text.replace(QString("kala,"), QString("魚,"));
  text.replace(QString("kalama,"), QString("音,"));
  text.replace(QString("kama,"), QString("来,"));
  text.replace(QString("kasi,"), QString("木,"));
  text.replace(QString("kepeken,"), QString("使,"));
  text.replace(QString("kili,"), QString("果,"));
  text.replace(QString("kipisi,"), QString("切,"));
  text.replace(QString("kiwen,"), QString("石,"));
  text.replace(QString("kon,"), QString("空,"));
  text.replace(QString("kule,"), QString("色,"));
  text.replace(QString("kute,"), QString("聞,"));
  text.replace(QString("kulupu,"), QString("群,"));
  text.replace(QString("lape,"), QString("眠,"));
  text.replace(QString("laso,"), QString("青,"));
  text.replace(QString("lawa,"), QString("首,"));
  text.replace(QString("lete,"), QString("冷,"));
  text.replace(QString("lili,"), QString("小,"));
  text.replace(QString("linja,"), QString("糸,"));
  text.replace(QString("lipu,"), QString("葉,"));
  text.replace(QString("loje,"), QString("赤,"));
  text.replace(QString("lon,"), QString("在,"));
  text.replace(QString("luka,"), QString("手,"));
  text.replace(QString("lukin,"), QString("見,"));
  text.replace(QString("lupa,"), QString("穴,"));
  text.replace(QString("mama,"), QString("母,"));
  text.replace(QString("mani,"), QString("貝,"));
  text.replace(QString("meli,"), QString("女,"));
  text.replace(QString("mi,"), QString("私,"));
  text.replace(QString("mije,"), QString("男,"));
  text.replace(QString("moku,"), QString("食,"));
  text.replace(QString("moli,"), QString("死,"));
  text.replace(QString("monsi,"), QString("後,"));
  text.replace(QString("mu,"), QString("む,"));
  text.replace(QString("mun,"), QString("月,"));
  text.replace(QString("musi,"), QString("楽,"));
  text.replace(QString("mute,"), QString("多,"));
  text.replace(QString("namako,"), QString("冗,"));
  text.replace(QString("nanpa,"), QString("番,"));
  text.replace(QString("nasa,"), QString("狂,"));
  text.replace(QString("nasin,"), QString("道,"));
  text.replace(QString("nena,"), QString("丘,"));
  text.replace(QString("nimi,"), QString("称,"));
  text.replace(QString("noka,"), QString("足,"));
  text.replace(QString("oko,"), QString("目,"));
  text.replace(QString("olin,"), QString("愛,"));
  text.replace(QString("open,"), QString("開,"));
  text.replace(QString("pakala,"), QString("打,"));
  text.replace(QString("pali,"), QString("作,"));
  text.replace(QString("palisa,"), QString("棒,"));
  text.replace(QString("pan,"), QString("米,"));
  text.replace(QString("pana,"), QString("授,"));
  text.replace(QString("pata,"), QString("氏,"));
  text.replace(QString("pilin,"), QString("心,"));
  text.replace(QString("pimeja,"), QString("黒,"));
  text.replace(QString("pini,"), QString("終,"));
  text.replace(QString("pipi,"), QString("虫,"));
  text.replace(QString("poka,"), QString("側,"));
  text.replace(QString("poki,"), QString("箱,"));
  text.replace(QString("pona,"), QString("良,"));
  text.replace(QString("sama,"), QString("同,"));
  text.replace(QString("seli,"), QString("火,"));
  text.replace(QString("selo,"), QString("皮,"));
  text.replace(QString("seme,"), QString("何,"));
  text.replace(QString("sewi,"), QString("上,"));
  text.replace(QString("sijelo,"), QString("体,"));
  text.replace(QString("sike,"), QString("丸,"));
  text.replace(QString("sin,"), QString("新,"));
  text.replace(QString("sina,"), QString("君,"));
  text.replace(QString("sinpin,"), QString("前,"));
  text.replace(QString("sitelen,"), QString("画,"));
  text.replace(QString("sona,"), QString("知,"));
  text.replace(QString("soweli,"), QString("猫,"));
  text.replace(QString("suli,"), QString("大,"));
  text.replace(QString("suno,"), QString("日,"));
  text.replace(QString("supa,"), QString("面,"));
  text.replace(QString("suwi,"), QString("甜,"));
  text.replace(QString("tan,"), QString("因,"));
  text.replace(QString("taso,"), QString("許,"));
  text.replace(QString("tawa,"), QString("去,"));
  text.replace(QString("telo,"), QString("水,"));
  text.replace(QString("tenpo,"), QString("时,"));
  text.replace(QString("toki,"), QString("言,"));
  text.replace(QString("tomo,"), QString("家,"));
  text.replace(QString("tu,"), QString("二,"));
  text.replace(QString("unpa,"), QString("盛,"));
  text.replace(QString("uta,"), QString("口,"));
  text.replace(QString("utala,"), QString("戦,"));
  text.replace(QString("walo,"), QString("白,"));
  text.replace(QString("wan,"), QString("一,"));
  text.replace(QString("waso,"), QString("鳥,"));
  text.replace(QString("wawa,"), QString("力,"));
  text.replace(QString("weka,"), QString("遥,"));
  text.replace(QString("wile,"), QString("要,"));
  //common endings of words must be placed after original replacements
  text.replace(QString("ona,"), QString("彼,"));
  text.replace(QString("ala,"), QString("無,"));
  text.replace(QString("la,"), QString("ら,"));
  text.replace(QString("kin,"), QString("又,"));
  text.replace(QString("jelo,"), QString("黄,"));
  text.replace(QString("ken,"), QString("能,"));
  text.replace(QString("len,"), QString("布,"));
  text.replace(QString("en,"), QString("ん,"));
  text.replace(QString("pi,"), QString("ぴ,"));
  text.replace(QString("ni,"), QString("此,"));
  text.replace(QString("ma,"), QString("土,"));
  text.replace(QString("li,"), QString("り,"));
  text.replace(QString("ko,"), QString("粉,"));
  text.replace(QString("a,"), QString("あ,"));
  text.replace(QString("o,"), QString("お,"));
  text.replace(QString("e,"), QString("え,"));
  text.replace(QString("?"), QString("？"));//japanese question-mark
  text.replace(QString(". "), QString("。"));//japanese period
  text.replace(QString("。 "), QString("。"));//japanese period
  text.replace(QString("."), QString("。"));//japanese period
  text.replace(QString(" \n "), QString("\n"));//additional spaces no longer needed
  return text;
}
